// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'esp32-45a70',
    authDomain: 'esp32-45a70.firebaseapp.com',
    databaseURL: 'https://esp32-45a70-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-45a70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'esp32-45a70',
    authDomain: 'esp32-45a70.firebaseapp.com',
    databaseURL: 'https://esp32-45a70-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-45a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'esp32-45a70',
    authDomain: 'esp32-45a70.firebaseapp.com',
    databaseURL: 'https://esp32-45a70-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-45a70.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'esp32-45a70',
    authDomain: 'esp32-45a70.firebaseapp.com',
    databaseURL: 'https://esp32-45a70-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-45a70.appspot.com',
  );
}

// IMPORTANT: Remplacez les valeurs YOUR_* par vos vraies clés API
// Vous pouvez les obtenir depuis la console Firebase :
// 1. Allez sur https://console.firebase.google.com/
// 2. Sélectionnez votre projet esp32-45a70
// 3. Allez dans Project Settings > General
// 4. Scrollez vers le bas pour voir vos apps et leurs configurations